---
title: "Discussie"
author: "Sibren Reekers"
date: '2023-06-09'
output: html_document
---


## Discussie 

In figuur 1 van grafiek f is te zien dat de hoeveelheid gezonde borst-stamcellen in het begin heel langzaam afneemt. Dit is te verklaren met het feit dat hoe jonger een mens is hoe hoger de rate van aanmaak gezonde borst-stamcellen is. Hoe ouder een mens wordt, hoe meer mutaties zullen voorkomen. Daarom verandert er weinig in de hoeveelheid gezonde borst-stamcellen over de merendeel van tijd. De exponentiële afname bij t ~ 80 is te verklaren aan de hand van de volgende grafieken.

Zoals te zien in de grafieken q en s neemt de hoeveelheid cellen die LOH krijgen langzaam toe. De toename van deze twee grafieken loopt samen met de afname van grafiek f. Wanneer er meer LOH optreedt in een TSG zal de functionaliteit van het TSG afnemen en wordt de tumor steeds minder onderdrukt. Het aantal tumor cellen (grafiek n) en geproduceerde MDEs (grafiek m)) zal toenemen. Hoe meer deze twee grafieken toenemen hoe minder gezonde borststamcellen er over zullen blijven. De hoeveelheid tumoren lijkt bij het eind een evenwicht te bereiken, dit zou te maken kunnen hebben met lak aan voedingsstoffen binnen de omgeving. Het gevolg daarvan is dat er geen exponentiële groei meer zal zijn.
