---
title: "Software model"
author: "Mark van de Streek"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Het software model

```{r}
library(deSolve)
```

```{r}
# Parameters
#parameters <- c(nf = 1, nq = 0.5, nr = 0.5, ns = 0.5, 
#                lambda.n = 0.75, lambda.q = 7.5e-3, 
#                lambda.r = 7.575e-3, lambda.s = 0.0375, 
#                m = 1, L1 = 0.000365, t = 1, A = 1, dm = 5.102041e-12, 
#                dn = 1e-9, p1 = 2e-7, p2 = 1e-6-1e-5, p3 = 1e-3, p4 = 1e-2,
#                y = 0.00005, nabla = 0, alfa = 1.01, f = 1e-11, b = 0,
#                n = 1, s = 1, r = 1, q = 1)

parameters <- c(
  lambda.n = 0.75, lambda.q = 7.5e-3, lambda.r = 7.575e-3, lambda.s = 0.0375,
  nf = 1, nq = 0.5, nr = 0.5, ns = 0.5,
  L1 = 0.000365,
  dm = 5.102041e-12, dn = 1e-9,
  p1 = 2e-7, p2 = 5e-6, p3 = 1e-3, p4 = 1e-2,
  y = 0.00005, b = 0, nabla = 0, alfa = 1.01,
  x = 0)

# Tijdssequentie
times <- 12:90

# Initiële waardes
initial.values <- c(f = 1e-11, q = 0, r = 0, s = 0, n = 0, m = 0)
```

```{r}
verandering <- function (time, parameters, initial.values) {
  with(as.list(c(parameters, initial.values)),{
    A <- n+f+q+r+s
    # Vergelijkingen
    df.dt <- - (nf * m * f) - (L1 * f)
    dq.dt <- (lambda.q * q * (1 - A)) - (nq * n * q) + (L1 * f) - (p2 * q)
    dr.dt <- (lambda.r * r * (1 - A)) - (nr * n * r) + (p2 * q) - (p3 * r)
    ds.dt <- (lambda.s * s * (1 - A)) - (ns * n * s) + (p3 * r) - (p4 * s)
    d.accent.n.dt <- (lambda.n * n * (1 - A)) + (dn * x) - (y * x * (n * x * f)) + (p4 * s)
    d.accent.m.dt <- (dm * x) + (alfa * n * (1 - m)) - (b * m)
    
    
    # Retourneren van de initiële waardes
    return(list(c(df.dt, dq.dt, dr.dt, ds.dt, d.accent.n.dt, d.accent.m.dt)))
  })
}
```

```{r}
out <- ode(y = initial.values, times = times, func = verandering, parms = parameters)
```



# Resultaten



```{r}
hist(out, xlim = c(30, 90))

```

```{r, fig.cap="In dit figuur worden zes verlopen geplot respectievelijk zoals de titels omschrijven. De plots worden berekend bij een afgeleide van nul. In alle grafieken is op de y-as de hoeveelheid stof te zien en dit verloopt over de x-as met elke tijdseenheid is één jaar. In grafiek f begint bij t~60 de hoeveelheid borststamcellen af te nemen tot t~74 richting y = 0. Verder loopt als gevolg van het verloop in grafiek f in grafiek (q) de hoeveelheid LOHs (bijna) exponentieel op van t~0 richting t~65. Deze hoeveelheid loopt vanaf jaar ~ 65 vervolgens weer af richting nul. Door de aanwezigheid van LOH op TSG1 wordt TSG1 uitgeschakeld. In grafiek r correspondeert het verloop van grafiek r met het verloop van grafiek q. Alleen loopt dit proces minder snel op. In grafiek s verloopt de aanwezigheid LOH op TSG2 relatief langzaam tot wederom t~65 en deze hoeveelheid neemt vervolgens fors af. In grafieken f, q, r, en s verlopen de afnames fors af tot t~80 richting y = 0. \\linebreak \\linebreak  Grafieken n en m tonen oorzaak en gevolg van elkaar. Want het aantal tumorcellen in grafiek n vanaf t~62 neemt fors toe en deze tumorcellen maken MDE enzymen om ruimte vrij te maken voor nieuwe tumorcellen. Dus in grafiek m zal vanaf t ~ 62 ook het aantal MDEs respectievelijk fors toenemen tot y~10.0, waar er een evenwicht wordt bereikt."}
par("mar"=c(5, 4, 4, 4))
plot(out, main = c("Fractie gezonde borststamcellen (f)", "Aanwezigheid LOH op TSG1 (q)",
                   "Concentratie uitgeschakelde TSG1 (r)", "Aanwezigheid LOH op TSG2 (s)",
                   "Aantal tumorcellen (n)", "Aantal tumor geproduceerd MDEs (m)"),
     xlab = "Tijd (jaren)", ylab = "Hoeveelheid van stof", col = "blue")
```



